name: GitHub Actions Demo
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Packages
        run: npm install --prefix ./client
      - name: Build Client
        run: npm run build --prefix ./client
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "afternoon-earth-14955" #Must be unique in Heroku
          heroku_email: "juancamejo93@gmail.com"
          appdir: "server" # <- This will point to the api folder in your projec
