name: GitHub Actions Demo
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Packages
        run: npm install --prefix ./client
      - name: Build Client
        run: npm run build --prefix ./client
      - name: Move and rename client folder
        run: |
          mv client/build client/static
          rm -r server/static
          mv client/static server
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "afternoon-earth-14955"
          heroku_email: "juancamejo93@gmail.com"
          appdir: "server" # <- This will point to the api folder in your projec
